import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} grid lg:grid-cols-2`}>
        <div className="hidden lg:block fixed inset-0 lg:w-1/2">
          <Image
            src="/splash.png"
            alt="splash"
            priority
            fill
            objectFit="cover"
          />
        </div>
        <div className="lg:col-start-2 lg:overflow-y-scroll">
          {children}
        </div>
      </body>
    </html>
  );
}
